{
  parserClass="jirolanguage.parser.JiroParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Jiro"
  psiImplClassSuffix="Impl"
  psiPackage="jirolanguage.psi"
  psiImplPackage="jirolanguage.psi.impl"

  elementTypeHolderClass="jirolanguage.psi.JiroTypes"
  elementTypeClass="jirolanguage.psi.JiroElementType"
  tokenTypeClass="jirolanguage.psi.JiroTokenType"

//  psiImplUtilClass="jirolanguage.psi.impl.JiroPsiImplUtil"
}

//jiroFile ::= (property|COMMENT)*
//
//property ::= (KEY SEPARATOR VALUE?)|KEY {
//    pin=3
//    recoverWhile="recover_property"
//    mixin="jirolanguage.psi.impl.JiroNamedElementImpl"
//    implements="jirolanguageugin.psi.JiroNamedElement"
//    methods=[getKey getValue getName setName getNameIdentifier getPresentation]
//}
//
//private recover_property ::= !(KEY|SEPARATOR|COMMENT)

jiroFile ::= item_*
private item_ ::= (property|LINE_COMMENT|BLOCK_COMMENT|DOC_COMMENT|CRLF)
property ::= SWITCH | (CASE1 SWITCH_VALUE) | (CASE2 SWITCH_VALUE) | (CASE3 SWITCH_VALUE) | (CASE4 SWITCH_VALUE) | (DEFAULT SWITCH_VALUE) | BREAK | CONTINUE | BRACKETS | CONSOLE_LOG | SEMICOLON | FUNCTION | RETURN | BRACKETS_LEFT | BRACKETS_RIGHT | INCREMENT | DECREMENT | TRUE | FALSE | (LET KEY) | (SEPARATOR  VALUE)